apiVersion: apps/v1
kind: Deployment

metadata:
  name: users-service-v2

  labels:
    app: users-service
    version: v2

spec:
  replicas: 1

  selector:
    matchLabels:
      app: users-service
      version: v2

  template:
    metadata:
      labels:
        app: users-service
        version: v2

    spec:
      containers:
        - name: users-service
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/users-service:${{ github.sha }}

          ports:
            - containerPort: 8000

          env:
            - name: VERSION
              value: "v2"
