replicaCount: 2
image:
  repository: 106551436513.dkr.ecr.us-east-1.amazonaws.com/payments-service
  tag: "c1655c2605196cfba31b7dc3f708b9f582131244"
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
  env:
  - name: OTEL_SERVICE_NAME
    value: payments-service

  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://otel-collector.observability.svc.cluster.local:4318
