apiVersion: apps/v1
kind: Deployment

metadata:
  name: users-service-v2

  labels:
    app: users-service
    version: v2

spec:
  replicas: 1

  selector:
    matchLabels:
      app: users-service
      version: v2

  template:
    metadata:
      labels:
        app: users-service
        version: v2

    spec:
      containers:
        - name: users-service
          image: <your-ecr>/users-service:<NEW_TAG>

          ports:
            - containerPort: 8000
